services:

  mysqldb:
    container_name: mysqlcontainer
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: maternycaredb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports: 
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb 
      DB_USER: admin
      DB_PASSWORD: 'letmein'
      DB_NAME: maternycaredb   
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 100
      SERVER_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge